Project.create(:title => 'Семья')
Todo.create(:text => 'Купить молоко', :isCompleted => false, :project_id => 1)
Todo.create(:text => 'Заменить масло в двигателе до 23 апреля', :isCompleted => false, :project_id => 1)
Todo.create(:text => 'Отправить письмо бабушке', :isCompleted => true, :project_id => 1)
Todo.create(:text => 'Заплатить за квартиру', :isCompleted => false, :project_id => 1)
Todo.create(:text => 'Забрать обувь из ремонта', :isCompleted => false, :project_id => 1)
Project.create(:title => 'Работа')
Todo.create(:text => 'Позвонить заказчику', :isCompleted => true, :project_id => 2)
Todo.create(:text => 'Отправить документы', :isCompleted => true, :project_id => 2)
Todo.create(:text => 'Заполнить отчет', :isCompleted => false, :project_id => 2)
Project.create(:title => 'Прочее')
Todo.create(:text => 'Позвонить другу', :isCompleted => false, :project_id => 3)
Todo.create(:text => 'Подготовиться к поездке', :isCompleted => false, :project_id => 3)